# Import

In [137]:
import pandas as pd
import numpy as np

In [138]:
PATH_DATA_BASE = r'C:\Users\gusta\Desktop\GCB_PYTHON\Machine Learning and Data Science'\
                 r'\Machine Learning e Data Science com Python de A à Z\Bases de dados/'
census_df = pd.read_csv(PATH_DATA_BASE+'census.csv')

In [139]:
census_df

age          workclass  final-weight    education  education-num  \
0       39          State-gov         77516    Bachelors             13   
1       50   Self-emp-not-inc         83311    Bachelors             13   
2       38            Private        215646      HS-grad              9   
3       53            Private        234721         11th              7   
4       28            Private        338409    Bachelors             13   
...    ...                ...           ...          ...            ...   
32556   27            Private        257302   Assoc-acdm             12   
32557   40            Private        154374      HS-grad              9   
32558   58            Private        151910      HS-grad              9   
32559   22            Private        201490      HS-grad              9   
32560   52       Self-emp-inc        287927      HS-grad              9   

            marital-status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loos  hour-per-week  native-country  \
0         Male          2174             0             40   United-States   
1         Male             0             0             13   United-States   
2         Male             0             0             40   United-States   
3         Male             0             0             40   United-States   
4       Female             0             0             40            Cuba   
...        ...           ...           ...            ...             ...   
32556   Female             0             0             38   United-States   
32557     Male             0             0             40   United-States   
32558   Female             0             0             40   United-States   
32559     Male             0             0             20   United-States   
32560   Female         15024             0             40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [140]:
np.unique(census_df['income'], return_counts=True)[1]

array([24720,  7841], dtype=int64)

In [141]:
import plotly.express as px

In [142]:
census_df['income'].count().sum()

32561

In [143]:
px.bar(
    census_df,
    x = np.unique(census_df['income'], return_counts=True)[0],
    y = np.unique(census_df['income'], return_counts=True)[1],
    height = 500,
    color = np.unique(census_df['income'], return_counts=True)[0]
)

In [144]:
x_census = census_df.iloc[:, 0:14].values
x_census

array([[39, ' State-gov', 77516, ..., 0, 40, ' United-States'],
       [50, ' Self-emp-not-inc', 83311, ..., 0, 13, ' United-States'],
       [38, ' Private', 215646, ..., 0, 40, ' United-States'],
       ...,
       [58, ' Private', 151910, ..., 0, 40, ' United-States'],
       [22, ' Private', 201490, ..., 0, 20, ' United-States'],
       [52, ' Self-emp-inc', 287927, ..., 0, 40, ' United-States']],
      dtype=object)

In [145]:
y_census = census_df.iloc[:, 14].values
y_census

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [146]:
from sklearn.preprocessing import LabelEncoder
label_encoder_workclass = LabelEncoder()
label_encoder_education = LabelEncoder()
label_encoder_marital = LabelEncoder()
label_encoder_occupation = LabelEncoder()
label_encoder_relationship = LabelEncoder()
label_encoder_race = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_country = LabelEncoder()

In [147]:
x_census[:, 1] = label_encoder_workclass.fit_transform(x_census[:, 1])
x_census[:, 3] = label_encoder_education.fit_transform(x_census[:, 3])
x_census[:, 5] = label_encoder_marital.fit_transform(x_census[:, 5])
x_census[:, 6] = label_encoder_occupation.fit_transform(x_census[:, 6])
x_census[:, 7] = label_encoder_relationship.fit_transform(x_census[:, 7])
x_census[:, 8] = label_encoder_race.fit_transform(x_census[:, 8])
x_census[:, 9] = label_encoder_sex.fit_transform(x_census[:, 9])
x_census[:, 13] = label_encoder_country.fit_transform(x_census[:, 13])

In [148]:
x_census

array([[39, 7, 77516, ..., 0, 40, 39],
       [50, 6, 83311, ..., 0, 13, 39],
       [38, 4, 215646, ..., 0, 40, 39],
       ...,
       [58, 4, 151910, ..., 0, 40, 39],
       [22, 4, 201490, ..., 0, 20, 39],
       [52, 5, 287927, ..., 0, 40, 39]], dtype=object)

In [149]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
onehotencoder_census = ColumnTransformer(transformers = [('OneHot', OneHotEncoder(), [1, 3, 5, 6, 7, 8, 9, 13])], remainder = 'passthrough')
x_census = onehotencoder_census.fit_transform(x_census).toarray()
x_census

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 2.1740e+03, 0.0000e+00,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.3000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+01],
       ...,
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        4.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+01],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.5024e+04, 0.0000e+00,
        4.0000e+01]])

# Tomek Links

In [150]:
from imblearn.under_sampling import TomekLinks

In [151]:
tl = TomekLinks(sampling_strategy = 'all')
x_under, y_under = tl.fit_resample(x_census, y_census)

In [152]:
x_under.shape, y_under.shape

((27715, 108), (27715,))

In [153]:
np.unique(y_census, return_counts=True)

(array([' <=50K', ' >50K'], dtype=object), array([24720,  7841], dtype=int64))

In [154]:
np.unique(y_under, return_counts=True)

(array([' <=50K', ' >50K'], dtype=object), array([22297,  5418], dtype=int64))

In [155]:
from sklearn.model_selection import train_test_split
x_census_treinamento_under, x_census_teste_under, y_census_treinamento_under, y_census_teste_under = train_test_split(x_under, y_under, test_size=0.15, random_state=0)

In [156]:
x_census_treinamento_under.shape, x_census_teste_under.shape

((23557, 108), (4158, 108))

In [157]:
from sklearn.ensemble import RandomForestClassifier
random_forest_census = RandomForestClassifier(n_estimators=70, criterion='entropy', random_state=0)
random_forest_census.fit(x_census_treinamento_under, y_census_treinamento_under)

RandomForestClassifier(criterion='entropy', n_estimators=70, random_state=0)

In [158]:
from sklearn.metrics import accuracy_score
previsoes = random_forest_census.predict(x_census_teste_under)
accuracy_score(y_census_teste_under, previsoes)

0.8965848965848966

# SMOTE

In [159]:
from imblearn.over_sampling import SMOTE

In [160]:
smote = SMOTE(sampling_strategy='minority')
x_over, y_over = smote.fit_resample(x_census, y_census)

In [161]:
x_over.shape

(49440, 108)

In [162]:
np.unique(y_census, return_counts=True)

(array([' <=50K', ' >50K'], dtype=object), array([24720,  7841], dtype=int64))

In [163]:
np.unique(y_over, return_counts=True)

(array([' <=50K', ' >50K'], dtype=object), array([24720, 24720], dtype=int64))

In [164]:
from sklearn.model_selection import train_test_split
x_census_treinamento_over, x_census_teste_over, y_census_treinamento_over, y_census_teste_over = train_test_split(x_over, y_over, test_size=0.15, random_state=0)

In [165]:
x_census_treinamento_over.shape, x_census_teste_over.shape

((42024, 108), (7416, 108))

In [166]:
from sklearn.ensemble import RandomForestClassifier
random_forest_census = RandomForestClassifier(n_estimators=70, criterion='entropy', random_state=0)
random_forest_census.fit(x_census_treinamento_over, y_census_treinamento_over)

RandomForestClassifier(criterion='entropy', n_estimators=70, random_state=0)

In [167]:
from sklearn.metrics import accuracy_score
previsoes = random_forest_census.predict(x_census_teste_over)
accuracy_score(y_census_teste_over, previsoes)

0.9064185544768069