In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [3]:
with open('./Machine Learning e Data Science com Python de A à Z/Bases de dados/risco_credito.pkl', 'rb') as f:
    x_risco_credit, y_risco_credit = pickle.load(f)

In [4]:
x_risco_credit

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [5]:
y_risco_credit

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [6]:
lista_index = []
for i in range(0, len(y_risco_credit)):
    if y_risco_credit[i] == 'moderado':
        lista_index.append(i)
lista_index

[2, 7, 11]

In [7]:
x_risco_credit = np.delete(x_risco_credit, [2, 7, 11], axis=0)
y_risco_credit = np.delete(y_risco_credit, [2, 7, 11], axis=0)

In [8]:
x_risco_credit

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [9]:
y_risco_credit

array(['alto', 'alto', 'alto', 'baixo', 'baixo', 'alto', 'baixo', 'baixo',
       'alto', 'baixo', 'alto'], dtype=object)

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
logistic_risco_credit = LogisticRegression(random_state=1)
logistic_risco_credit.fit(x_risco_credit, y_risco_credit)

LogisticRegression(random_state=1)

In [12]:
logistic_risco_credit.intercept_

array([-0.80828993])

In [13]:
logistic_risco_credit.coef_

array([[-0.76704533,  0.23906678, -0.47976059,  1.12186218]])

In [14]:
# história boa (0), dívida alta (0), garantias nenhuma (1), renda > 35 (2)
# história ruim (2), dívida alta (0), garantias adequada (0), renda < 15 (0)
previsao = logistic_risco_credit.predict([[0,0,1,2], [2,0,0,0]])
previsao

array(['baixo', 'alto'], dtype=object)

In [ ]:
from sklearn.model_selection import GridSearchCV
x_credit = np.concatenate((x_credit_treinamento, x_credit_teste), axis=0)
y_credit = np.concatenate((y_credit_treinamento, y_credit_teste), axis=0)
print(x_credit.shape)
print(x_credit.shape)
parameters = {'n_neighbors': [2, 3, 5, 10, 20, 50],
              'p': [1, 2],
              'weights': ['uniform', 'distance'],
              'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']}
grid_search = GridSearchCV(estimator=LogisticRegression(), param_grid=parameters)
grid_search.fit(x_credit, y_credit)
best_parameters = grid_search.best_params_
best_score = grid_search.best_score_
print(best_parameters)
print(best_score)