In [2]:
import gym
import random

In [5]:
env = gym.make('Taxi-v3').env

In [21]:
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [22]:
env.reset()
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [23]:
# 0 -> South, 1 -> North, 2 -> East, 3-> West, 4 -> PickUp, 5 -> DropOff
print(env.action_space)

Discrete(6)


In [24]:
print(env.observation_space)

Discrete(500)


In [25]:
5*5*5*4

500

In [26]:
len(env.P)

500

In [27]:
env.P[484]

{0: [(1.0, 484, -1, False)],
 1: [(1.0, 384, -1, False)],
 2: [(1.0, 484, -1, False)],
 3: [(1.0, 464, -1, False)],
 4: [(1.0, 484, -10, False)],
 5: [(1.0, 484, -10, False)]}

Diferença temporal (Q-learning)

<img src="./image.png" style="background-color: white; width: 600px" >

In [6]:
import numpy as np
q_table = np.zeros([env.observation_space.n, env.action_space.n])
q_table.shape

(500, 6)

In [7]:
q_table

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [1]:
from IPython.display import clear_output

In [30]:
# 1-10% 3-90%
# exploration / exploitation
# 0 = south 1 = north 2 = east 3 = west 4 = pickup 5 = dropoff

alpha = 0.1
gamma = 0.6
epsilon = 0.1

for i in range(100000):
    state = env.reset()
    penalty, reward = 0, 0
    done = False
    while not done:
        # Exploration
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()
        # Exploitation
        else:
            action = np.argmax(q_table[state])

        next_state, reward, done, info = env.step(action)

        old_q = q_table[state, action]
        next_max = np.max(q_table[next_state])

        new_q = (1 - alpha) * old_q + alpha * (reward + gamma * next_max)
        q_table[state, action] = new_q

        if reward == -10:
            penalty += 1

        state = next_state

        if i % 100 == 0:
            clear_output(wait=True)
            print('Episode: ', i)

print('Training completed!')

Episode:  99900
Training completed!


In [32]:
q_table[424]

array([-2.49489606, -2.4936525 , -2.4936525 , -2.49438271, -9.25682457,
       -8.45843723])

In [33]:
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)


In [63]:
env.reset()
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [64]:
env.encode(0, 3, 3, 0)

72

In [68]:
# 0 -> South, 1 -> North, 2 -> East, 3 -> West, 4 -> PickUp, 5 -> DropOff
q_table[72]

array([-2.4510224 , -2.46399588, -2.47575797, -2.47309848, -8.98977543,
       -9.69287567])

In [82]:
total_penaltys = 0
episodes = 50
frames = []

for _ in range(episodes):
    state = env.reset()
    penaltys, reward = 0, 0
    done = False
    while not done:
        action = np.argmax(q_table[state])
        state, reward, done, info = env.step(action)

        if reward == -10:
            penaltys += 1
    
        frames.append({
            'frame': env.render(mode='ansi'),
            'state': state,
            'action': action,
            'reward': reward
        })

    total_penaltys += penaltys

print('Episodes: ', episodes)
print('Penaltys: ', total_penaltys)

Episodes:  50
Penaltys:  0


In [8]:
from time import sleep
for frame in frames:
  clear_output(wait=True)
  print(frame['frame'])
  print('State', frame['state'])
  print('Action', frame['action'])
  print('Reward', frame['reward'])
  sleep(.5)

NameError: name 'frames' is not defined